#! /bin/sh

regenerate ()
(
    dist="$1"
    destdir="$2"
    cd "cont-postgresql"
    git submodule init
    git submodule update
    make clean DESTDIR="$destdir"
    make distro="$dist" DESTDIR="$destdir"
)

cat tasks | while read dist dir; do
  test -z "$dist" && continue

  destdir=`pwd`"/$dir"
  echo "$destdir"
  regenerate "$dist" "$destdir" || exit 1
done
